# Generated by Django 3.2.10 on 2022-01-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nick_name',
        ),
    ]
