# Generated by Django 3.2.10 on 2022-01-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=120, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=14, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(help_text='Please enter your beautiful photo, free to pose, but use decent clothing.', upload_to='', verbose_name='Photo profile'),
        ),
    ]
