# Generated by Django 3.2.11 on 2022-01-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220117_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(help_text='Please enter your beautiful photo, free to pose, but use decent clothing.', upload_to='photo_profile/', verbose_name='Photo profile'),
        ),
    ]
