# Generated by Django 3.2.10 on 2021-12-31 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BestFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(help_text='Enter your instagram username with the @, i.e: @ziyk123.', max_length=35, verbose_name='Instagram Account')),
                ('chield_number', models.CharField(max_length=2, verbose_name='Chield Number')),
                ('number_of_sibling', models.CharField(max_length=2, verbose_name='Number of sibling(s).')),
                ('klass', models.CharField(help_text='Enter your class name, i.e: XII TJAT-2. HARUS tulis seperti contoh.', max_length=13, verbose_name='Class')),
                ('friend', models.ManyToManyField(to='students.BestFriends', verbose_name='Best Friends')),
            ],
        ),
        migrations.CreateModel(
            name='MotherStudentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('jobs', models.CharField(max_length=100, verbose_name='Jobs')),
                ('chield', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FatherStudentModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('jobs', models.CharField(max_length=100, verbose_name='Jobs')),
                ('chield', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
