# Generated by Django 3.2.10 on 2022-01-17 03:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='friend',
        ),
        migrations.AddField(
            model_name='bestfriends',
            name='friend',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='klass',
            field=models.CharField(help_text='Enter your class name, i.e: XII TJAT-2. MUST write as example.', max_length=13, verbose_name='Class'),
        ),
    ]
