# Generated by Django 3.2.10 on 2022-01-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatherstudentmodels',
            old_name='chield',
            new_name='child',
        ),
        migrations.RenameField(
            model_name='motherstudentmodels',
            old_name='chield',
            new_name='child',
        ),
    ]
