# Generated by Django 3.2.10 on 2022-01-18 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20220117_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatherstudentmodels',
            old_name='jobs',
            new_name='father_jobs',
        ),
        migrations.RenameField(
            model_name='motherstudentmodels',
            old_name='jobs',
            new_name='mother_jobs',
        ),
    ]
