# Generated by Django 3.2.10 on 2022-01-18 05:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0007_auto_20220118_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BestFriends',
            new_name='BestFriendsModel',
        ),
    ]
