# Generated by Django 3.2.10 on 2022-01-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_bestfriends_bestfriendsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestfriendsmodel',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone Number'),
        ),
    ]
