# Generated by Django 3.2.10 on 2022-01-18 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0009_alter_bestfriendsmodel_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(verbose_name='Approval')),
                ('date', models.DateField(help_text='Enter what date for when you want meet the teacher.', verbose_name='Appointment date')),
                ('time', models.TimeField(help_text='Enter what time for when you want meet the teacher.', verbose_name='Appointment time at')),
                ('desc', models.TextField(verbose_name='Description')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('techer', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
