# Generated by Django 3.2.10 on 2022-01-19 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0010_appointmentschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentschedule',
            name='approved',
            field=models.BooleanField(null=True, verbose_name='Approval'),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='desc',
            field=models.TextField(help_text='Describe why you make an appointment.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='appointmentschedule',
            name='techer',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
