# Generated by Django 3.2.10 on 2022-01-19 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20220119_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentschedule',
            old_name='techer',
            new_name='teacher',
        ),
    ]
