# Generated by Django 3.2.11 on 2022-01-21 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssesmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Assesment Name')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=120, verbose_name='Question')),
                ('img_question', models.ImageField(blank=True, null=True, upload_to='question_img/', verbose_name='Question Image')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assesmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=120, verbose_name='Answer')),
                ('img_question', models.ImageField(blank=True, null=True, upload_to='answer_img/', verbose_name='Question Image')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.questionmodel')),
            ],
        ),
    ]
