# Generated by Django 3.2.11 on 2022-01-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='img_question',
            new_name='answer_img',
        ),
    ]
